spring:
  application:
    name: "OAuth2_Client_Sample"
  profiles:
    active: "dev"
  security:
    oauth2:
      client:
        registration:
          oauth2-client-sample:
            client-id: "test-client"
            client-secret: "5"
            client-authentication-method: "client_secret_post"
            authorization-grant-type: "client_credentials"

server:
  error:
    whitelabel:
      enabled: "false"

apiPrefix: "/api"
